config/routes.rb
Rails.application.routes.draw do

  get 'index' => 'welcome#index'
  get 'build' => 'welcome#build'
  get 'company' => 'welcome#company'
  get 'contact' => 'welcome#contact'
  get 'shop' => 'welcome#shop'
  get 'admin' => 'welcome#admin'
  get 'terms' => 'welcome#terms'
  get 'support' => 'welcome#support'
  get 'drums/admin'
  get 'artists/admin'

  resources :artists
  resources :contents
  resources :drums

  root 'welcome#index'

  match '/contacts',     to: 'contacts#new',             via: 'get'
  resources "contacts", only: [:new, :create]

end

app/models/content.rb
class Content < ActiveRecord::Base
end

app/controllers/contents_controller.rb
class ContentsController < ApplicationController

  http_basic_authenticate_with :name => ENV['ADMIN_USER'], :password => ENV['ADMIN_PASS'], except: [:index, :show]

  before_action :set_is_admin
  before_action :set_content, only: [:show, :edit, :update, :destroy]

  def index
    @contents = Content.all
  end

  def show
  end

  def new
    @content = Content.new
  end

  def edit
  end

  def create
    @content = Content.new(content_params)

    respond_to do |format|
      if @content.save
        format.html { redirect_to contents_path, notice: 'Content was successfully created.' }
        format.json { render :show, status: :created, location: @content }
      else
        format.html { render :new }
        format.json { render json: @content.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @content.update(content_params)
        format.html { redirect_to contents_path, notice: 'Content was successfully updated.' }
        format.json { render :show, status: :ok, location: @content }
      else
        format.html { render :edit }
        format.json { render json: @content.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @content.destroy
    respond_to do |format|
      format.html { redirect_to contents_url, notice: 'Content was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_content
      @content = Content.find(params[:id])
    end

    def set_is_admin
      @is_admin = true
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def content_params
      params.require(:content).permit(:content_text, :content_key)
    end
end

app/views/contents/_form.html.erb
<%= form_for(@content) do |f| %>
  <% if @content.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@content.errors.count, "error") %> prohibited this content from being saved:</h2>

      <ul>
      <% @content.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <% if @content.new_record? %>
  <div class="field">
    <%= f.text_field :content_key, class: "form-control", placeholder: "Content Key" %>
    <br>
  </div>
  <% end %>

  <div class="field">
    <%= f.text_area :content_text, rows: "8", class: "form-control", placeholder: "Content" %>
    <br>
  </div>


  <div class="actions">
    <%= f.submit class: "btn-inverse btn-primary btn-sm" %>
    <%= link_to 'cancel', contents_path, class: "pull-right" %>
  </div>
<% end %>

app/views/contents/edit.html.erb
<div class="container">

  <!-- ADMIN MENU -->
  <div class="col-md-4">
    <div class="well">
      <%= render 'layouts/admin_menu' %>
    </div>
  </div>

  <!-- CONTENT -->
  <div class="col-md-8">
    <div class="well">
      <%= render 'form' %>
    </div>

  </div>

</div>

app/views/contents/index.html.erb
<div class="container">

  <!-- ADMIN MENU -->
  <div class="col-md-4">
    <div class="well">
      <%= render 'layouts/admin_menu' %>
    </div>
  </div>

  <!-- CONTENT -->
  <div class="col-md-8">

    <div class="well">
      <%= link_to "Add Content Section", new_content_path %><span class="glyphicon glyphicon-lock pull-right"></span>
    </div>

    <% @contents.each do | content | %>
    <div class="well">
      <h2><%= content.content_key %><%= link_to 'Edit', edit_content_path(content.id), class: "pull-right" %></h2>
      <hr>
      <%= strip_tags(content.content_text.truncate(500)) %><br><br>

    </div>
    <% end %>

  </div>

</div>

app/views/contents/new.html.erb
<div class="container">

  <!-- ADMIN MENU -->
  <div class="col-md-4">
    <div class="well">
      <%= render 'layouts/admin_menu' %>
    </div>
  </div>

  <!-- CONTENT -->
  <div class="col-md-8">
    <div class="well">
      <%= render 'form' %>
    </div>
  </div>

</div>