config/routes.rb
Rails.application.routes.draw do

  get 'index' => 'welcome#index'
  get 'build' => 'welcome#build'
  get 'company' => 'welcome#company'
  get 'contact' => 'welcome#contact'
  get 'shop' => 'welcome#shop'
  get 'admin' => 'welcome#admin'
  get 'terms' => 'welcome#terms'
  get 'support' => 'welcome#support'
  get 'drums/admin'
  get 'artists/admin'

  resources :artists
  resources :contents
  resources :drums

  root 'welcome#index'

  match '/contacts',     to: 'contacts#new',             via: 'get'
  resources "contacts", only: [:new, :create]

end

app/models/artist.rb
class Artist < ActiveRecord::Base
  mount_uploader :artist_img, PhotoUploader
  mount_uploader :artist_hero_img, PhotoUploader
  mount_uploader :kit_img, PhotoUploader
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController

  before_action :set_artist, only: [:show, :edit, :update, :destroy]

  http_basic_authenticate_with :name => ENV['ARTIST_USER'], :password => ENV['ARTIST_PASS'], except: [:index, :show]

  # GET /artists
  # GET /artists.json
  def index
    @artists = Artist.all
    @title = "artists"
  end

  def admin
    @artists = Artist.all
    @is_admin = true
  end

  # GET /artists/1
  # GET /artists/1.json
  def show
  end

  # GET /artists/new
  def new
    @artist = Artist.new
    @is_admin = true
  end

  # GET /artists/1/edit
  def edit
    @is_admin = true
  end

  # POST /artists
  # POST /artists.json
  def create
    @artist = Artist.new(artist_params)

    respond_to do |format|
      if @artist.save
        format.html { redirect_to artists_admin_path, notice: 'Artist was successfully created.' }
        format.json { render :show, status: :created, location: @artist }
      else
        format.html { render :new }
        format.json { render json: @artist.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /artists/1
  # PATCH/PUT /artists/1.json
  def update
    respond_to do |format|
      if @artist.update(artist_params)
        format.html { redirect_to artists_admin_path, notice: 'Artist was successfully updated.' }
        format.json { render :show, status: :ok, location: @artist }
      else
        format.html { render :edit }
        format.json { render json: @artist.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /artists/1
  # DELETE /artists/1.json
  def destroy
    @artist.destroy
    respond_to do |format|
      format.html { redirect_to artists_admin_path, notice: 'Artist was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_artist
      @artist = Artist.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def artist_params
      params.require(:artist).permit(:artist_name, :artist_band, :artist_img, :artist_hero_img, :artist_bio, :artist_bio_src, :kit_specs, :kit_material, :kit_finish, :kit_img, :social_inst, :social_fb, :social_twit)
    end
end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/views/artists/_form.html.erb
<%= form_for(@artist) do |f| %>
  <% if @artist.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@artist.errors.count, "error") %> prohibited this artist from being saved:</h2>

      <ul>
      <% @artist.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <h2>Artist Details</h2>
    <hr>

    <%= f.text_field :artist_name, class: "form-control", placeholder: "Drummer Name" %>
    <br>
  </div>
  <div class="field">
    <%= f.text_field :artist_band, class: "form-control", placeholder: "Band or Artist Name" %>
    <br>
  </div>
  <div class="field">
    <%= f.text_area :artist_bio, rows: "8", class: "form-control", placeholder: "Biography" %>
    <br>
  </div>
  <div class="field">
    <%= f.text_field :artist_bio_src, class: "form-control", placeholder: "Source of Biography" %>
    <br>
  </div>

  <br>
  <h2>Artist Image (640x640)</h2>
  <hr>
  <%= f.file_field :artist_img %>
  <br>

  <br>
  <h2>Header Image (1440x500)</h2>
  <hr>
  <%= f.file_field :artist_hero_img %>
  <br>

  <br>
  <h2>Kit Details</h2>
  <hr>

  <div class="field">
    <%= f.text_field :kit_specs, class: "form-control", placeholder: "Specifications" %>
    <br>
  </div>
  <div class="field">
    <%= f.text_field :kit_material, class: "form-control", placeholder: "Material" %>
    <br>
  </div>
  <div class="field">
    <%= f.text_field :kit_finish, class: "form-control", placeholder: "Finish" %>
    <br>
  </div>

  <br>
  <h2>Kit Photo (600x450)</h2>
  <hr>
  <%= f.file_field :kit_img %>
  <br>

  <br><br>
  <h2>Social Media</h2>
  <hr>

  <div class="field">
    <%= f.text_field :social_inst, class: "form-control", placeholder: "Instagram" %>
    <br>
  </div>
  <div class="field">
    <%= f.text_field :social_fb, class: "form-control", placeholder: "Facebook" %>
    <br>
  </div>
  <div class="field">
    <%= f.text_field :social_twit, class: "form-control", placeholder: "Twitter" %>
    <br>
  </div>
  <br>
  <div class="actions">
    <%= f.submit class: "btn-inverse btn-primary btn-sm" %>

    <% if !@artist.new_record? %>
    <%= link_to 'Delete', @artist, method: :delete, data: { confirm: 'Are you sure you want to delete this artist?' }, class: "pull-right" %>
    <% end %>
  </div>
  <br>
<% end %>

app/views/artists/admin.html.erb
<div class="container">

  <!-- ADMIN MENU -->
  <div class="col-md-4">
    <div class="well">
      <%= render 'layouts/admin_menu' %>
    </div>
  </div>

  <!-- CONTENT -->
  <div class="col-md-8">

    <div class="well">
      <%= link_to 'Add Artist', new_artist_path(@artist) %><span class="glyphicon glyphicon-lock pull-right"></span>
    </div>

    <div class="well">

      <table class="table">
        <thead>
          <tr>
            <th>Artist</th>
            <th>Created</th>
            <th>Edit</th>
          </tr>
        </thead>

        <tbody>

          <% @artists = Artist.order("artist_name ASC") %>
          <% @artists.each do |artist| %>
          <tr>
            <td><%= link_to artist.artist_name, artist_path(artist) %></td>
            <td><%= artist.created_at.strftime("%b. %d %Y") %></td>
            <td><%= link_to 'Edit', edit_artist_path(artist.id) %></td>
          </tr>
          <% end %>

        </tbody>

      </table>

    </div>
  </div>

</div>

app/views/artists/edit.html.erb
<div class="container">

  <!-- ADMIN MENU -->
  <div class="col-md-4">
    <div class="well">
      <%= render 'layouts/admin_menu' %>
    </div>
  </div>

  <!-- CONTENT -->
  <div class="col-md-8">
    <div class="well">

      <%= render 'form' %>

    </div>
  </div>

    </div>
    </div>
  </div>

</div>

app/views/artists/index.html.erb
<div class="container">
  <div class="row">

    <% @artists.each do |artist| %>
    <div class="col-md-4 zero-col">
      <div class="img-640">

        <a href="<%= artist_path(artist) %>" class="meta-hover"><img src="<%= artist.artist_img %>">

          <div class="contenthover">
            <div class="hover-text-container">
              <div class="hover-text-head"><%= artist.artist_name %></div>
              <div class="hover-text-sub"><%= artist.artist_band %></div>
            </div>
          </div>
        </a>

      </div>

    </div>
    <% end %>

  </div>
</div>

app/views/artists/new.html.erb
<div class="container">

  <!-- ADMIN MENU -->
  <div class="col-md-4">
    <div class="well">
      <%= render 'layouts/admin_menu' %>
    </div>
  </div>

  <!-- CONTENT -->
  <div class="col-md-8">
    <div class="well">

      <%= render 'form' %>

    </div>
  </div>

</div>

app/views/artists/show.html.erb
<!-- MAIN CARD BODY -->

<div class="container">

  <div class="row">
    <div class="col-md-8">

      <div class="well">

        <h2>Biography</h2>
        <hr>
        <p class="p-bio"><%= @artist.artist_bio %></p>

        <hr>

        <div class="footer-copy">Source: <%= @artist.artist_bio_src %></div>

      </div>

    </div>



<!-- RIGHT CARD COL -->

    <div class="col-md-4">

      <div class="well artist-kit-well">

        <a href="<%= @artist.kit_img %>"><img src="<%= @artist.kit_img %>" width="100%"></a>

      </div>


      <div class="well">

        <h2>Kit Specifications</h2>
        <hr>

        <h2>Shells</h2>
        <p class="p-text"><%= @artist.kit_specs %></p>
        <p class="p-text"><%= @artist.kit_material %></p>

        <hr>

        <h2>Finish</h2>
        <p class="p-text"><%= @artist.kit_finish %></p>

      </div>


      <div class="well">
        <h2>Social Love</h2>
        <hr>
        <div class="text-center">
          <%=link_to image_tag('btn-inst.jpg', class:"artist-social"), @artist.social_inst %>
          <%=link_to image_tag('btn-twt.jpg', class:"artist-social"), @artist.social_twit %>
          <%=link_to image_tag('btn-fb.jpg', class:"artist-social"), @artist.social_fb %>
        </div>

      </div>

    </div>

  </div>
</div>