config/routes.rb
Rails.application.routes.draw do

  get 'index' => 'welcome#index'
  get 'build' => 'welcome#build'
  get 'company' => 'welcome#company'
  get 'contact' => 'welcome#contact'
  get 'shop' => 'welcome#shop'
  get 'admin' => 'welcome#admin'
  get 'terms' => 'welcome#terms'
  get 'support' => 'welcome#support'
  get 'drums/admin'
  get 'artists/admin'

  resources :artists
  resources :contents
  resources :drums

  root 'welcome#index'

  match '/contacts',     to: 'contacts#new',             via: 'get'
  resources "contacts", only: [:new, :create]

end

app/models/drum.rb
class Drum < ActiveRecord::Base
  default_scope {order(:release_date => :desc)}
  mount_uploader :photo, PhotoUploader
end

app/controllers/drums_controller.rb
class DrumsController < ApplicationController
  before_action :set_drum, only: [:show, :edit, :update, :destroy]

  http_basic_authenticate_with :name => ENV['ADMIN_USER'], :password => ENV['ADMIN_PASS'], except: [:index, :show]

  # GET /drums
  # GET /drums.json
  def index
    @drums = Drum.all
  end

  def admin
    @drums = Drum.all
    @is_admin = true
  end

  # GET /drums/1
  # GET /drums/1.json
  def show
  end

  # GET /drums/new
  def new
    @drum = Drum.new
    @drum.release_date = Time.now
    @is_admin = true
  end

  # GET /drums/1/edit
  def edit
    @is_admin = true
  end

  # POST /drums
  # POST /drums.json
  def create
    @drum = Drum.new(drum_params)

    respond_to do |format|
      if @drum.save
        format.html { redirect_to drums_admin_path, notice: 'Drum was successfully created.' }
        format.json { render :show, status: :created, location: @drum }
      else
        format.html { render :new }
        format.json { render json: @drum.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /drums/1
  # PATCH/PUT /drums/1.json
  def update
    respond_to do |format|
      if @drum.update(drum_params)
        format.html { redirect_to drums_admin_path, notice: 'Drum was successfully updated.' }
        format.json { render :show, status: :ok, location: @drum }
      else
        format.html { render :edit }
        format.json { render json: @drum.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /drums/1
  # DELETE /drums/1.json
  def destroy
    @drum.destroy
    respond_to do |format|
      format.html { redirect_to drums_admin_path, notice: 'Drum was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_drum
      @drum = Drum.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def drum_params
      params.require(:drum).permit(:drumTitle, :drumSize, :drumPhoto, :drumPrice, :drumCustomer, :drumCustomerSocial, :drumDetails, :release_date, :photo, :snare)
    end
end

app/helpers/drums_helper.rb
module DrumsHelper
end

app/views/drums/_drum_detail.html.erb
<!-- DRUM DETAIL MODAL -->

<div class="modal drum-detail" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" id="<%= "drum_modal_#{drum.id}" %>">
  <div class="modal-dialog modal-lg">
    <div class="modal-content">
      <div class="row">

          <div class="col-md-8">
            <img src="<%= drum.photo %>">
          </div>

          <div class="col-md-4">
            <br>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            <h2><%= drum.drumTitle %></h2>
            <hr>

            <h2>Sizes</h2>
            <p class="p-text"><%= drum.drumSize %></p>

            <h2>Details</h2>
            <p class="p-text"><%= drum.drumDetails %></p>

            <h2>Artist</h2>
            <p class="p-text"><a href="<%= drum.drumCustomerSocial %>"><%= drum.drumCustomer %></a></p>

            <hr>

            <center>
            <p class="p-label text-center"><%= drum.drumPrice %></p>
            <p><a class="btn-inverse btn-primary btn-sm text-center" href="#" role="button">build your own</a></p>
            <p class-"p-label"><%=link_to "Share", drum_path(drum) %></p>
          </center>

          </div>

      </div>
    </div>
  </div>
</div>

app/views/drums/_form.html.erb
<%= form_for(@drum) do |f| %>
  <% if @drum.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@drum.errors.count, "error") %> prohibited this drum from being saved:</h2>

      <ul>
      <% @drum.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <h2>Drum Details</h2>
    <hr>

  <div class="field">
    <%= f.text_area :drumDetails, rows: "8", class: "form-control" %>
    <br>
  </div>

  <h2>Drum Photo</h2>
  <hr>
  <div class="field">
    <%= f.file_field :photo %>
    <br>
    <hr>
  </div>

  <div class="actions">
    <%= f.submit class: "btn-inverse btn-primary btn-sm" %>

    <% if !@drum.new_record? %>
    <%= link_to 'Delete', @drum, method: :delete, data: { confirm: 'Are you sure you want to delete this drum?' }, class: "pull-right" %>
    <% end %>

  </div>
<% end %>

app/views/drums/admin.html.erb
<div class="container">

  <!-- ADMIN MENU -->
  <div class="col-md-4">
    <div class="well">
      <%= render 'layouts/admin_menu' %>
    </div>
  </div>

  <!-- CONTENT -->
  <div class="col-md-8">

    <div class="well">
      <%= link_to 'Add Drum to Gallery', new_drum_path(@drum) %><span class="glyphicon glyphicon-lock pull-right"></span>
    </div>

    <div class="well">

      <table class="table">
        <thead>
          <tr>
            <th>Drum</th>
            <th>Created</th>
            <th>Edit</th>
          </tr>
        </thead>

        <tbody>

          <% @drums = Drum.order("created_at desc") %>
          <% @drums.each do |drum| %>
          <tr>
            <td><a href="<%= drum_path(drum) %>"><img src="<%= drum.photo %>" class="drum-thumb"></a></td>
            <td><%= drum.created_at.strftime("%b. %d %Y") %></td>
            <td><%= link_to 'Edit', edit_drum_path(drum.id) %></td>
          </tr>
          <% end %>

        </tbody>

      </table>

    </div>
  </div>

</div>

app/views/drums/edit.html.erb
<!-- ADMIN HEADER -->
<div class="container-fluid basic-header">
  <div class="row">

    <div class="admin_close">
			<a href="/views">&times;</a>
		</div>

    <div class="text-center">
        <%=link_to image_tag('admin-logo.png', class:"basic-brand"), controller: "views" %>
    </div>
  </div>
</div>

<div class="container">

  <div class="section-title">
    edit drum
  </div>
  <hr>

    <div class="well">
      <%= render 'form' %>
    </div>

    <center>
      <%= link_to 'Delete Drum', @drum, method: :delete, data: { confirm: 'Are you sure you want to delete this drum?' } %>
    </center>

  </div>

app/views/drums/index.html.erb
<!-- USING ROOT FOR THIS PAGE -->

app/views/drums/new.html.erb
<div class="container">

  <!-- ADMIN MENU -->
  <div class="col-md-4">
    <div class="well">
      <%= render 'layouts/admin_menu' %>
    </div>
  </div>

  <!-- CONTENT -->
  <div class="col-md-8">
    <div class="well">
      <%= render 'form' %>
    </div>
  </div>

</div>

app/views/drums/show.html.erb
<div class="container vertical-center">
  <div class="drumwell row">

    <div class="show-content">

      <div class="col-md-8 modal-photo">
        <img class="drum-photo" src="<%= @drum.photo %>">
      </div>

      <div class="col-md-4 modal-right">
        <div class="modal-head">Details</div>

        <div class="modal-details">
          <p class="p-text"><%= @drum.drumDetails.html_safe %></p>

          <p class="created-at"><%= @drum.created_at.strftime("%b. %d %Y") %></p>

          <hr>

          <div class="share-links">
            <span class='st_facebook'></span>
            <span class='st_twitter'></span>
            <span class='st_pinterest'></span>
          </div>
        </div>
      </div>

    </div>

  </div>
</div>

<script type="text/javascript">var switchTo5x=true;</script>
<script type="text/javascript" id="st_insights_js" src="http://w.sharethis.com/button/buttons.js?publisher=d5c7a024-186e-4e30-a49d-e4e093368873"></script>
<script type="text/javascript">stLight.options({publisher: "d5c7a024-186e-4e30-a49d-e4e093368873", doNotHash: false, doNotCopy: false, hashAddressBar: false});</script>