config/routes.rb
Rails.application.routes.draw do

  get 'index' => 'welcome#index'
  get 'build' => 'welcome#build'
  get 'company' => 'welcome#company'
  get 'contact' => 'welcome#contact'
  get 'shop' => 'welcome#shop'
  get 'admin' => 'welcome#admin'
  get 'terms' => 'welcome#terms'
  get 'support' => 'welcome#support'
  get 'drums/admin'
  get 'artists/admin'

  resources :artists
  resources :contents
  resources :drums

  root 'welcome#index'

  match '/contacts',     to: 'contacts#new',             via: 'get'
  resources "contacts", only: [:new, :create]

end

app/views/layouts/_admin_header.html.erb
<div class="container-fluid basic-header">
  <div class="row">

    <div class="admin_close">
      <%= link_to "&times;".html_safe, root_path %>
		</div>

    <div class="text-center">
        <%=link_to image_tag('admin-logo.png', class:"basic-brand"), admin_path %>
    </div>
  </div>
</div>

app/views/layouts/_admin_menu.html.erb
<h2>Admin</h2>
<hr>

<%= link_to 'Drums', drums_admin_path %><span class="glyphicon glyphicon-lock pull-right"></span>
<hr>

<%= link_to 'Artists', artists_admin_path %><span class="glyphicon glyphicon-lock pull-right"></span>
<hr>

<%= link_to 'Site Content', contents_path %><span class="glyphicon glyphicon-lock pull-right"></span>

app/views/layouts/_artist_header.html.erb
<div class="jumbotron-artist" style="background: linear-gradient(rgba(50, 47, 51, 0.90), rgba(50, 47, 51, 0.90)), url('<%= @artist.artist_hero_img.blank? ? image_path("hero-2.jpg") : @artist.artist_hero_img %>'); background-position: center; background-size: cover; background-repeat: no-repeat;">
  <%= render 'layouts/header_nav' %>
  <div class="container hero-callout">
    <span class="jumbo-head"><%= @artist.artist_name %></span>
    <div class="artist-line"></div>
    <span class="jumbo-head-sub"><%= @artist.artist_band %></span>
  </div>
</div>

app/views/layouts/_footer.html.erb
<div class="container-fluid">
  <div class="row footer">

    <%=link_to image_tag('btn-inst.jpg', class:"footer-social"), "https://www.instagram.com/truthcustomdrums/" %>
    <%=link_to image_tag('btn-twt.jpg', class:"footer-social"), "https://twitter.com/TRUTHCSTMDRUMS" %>
    <%=link_to image_tag('btn-fb.jpg', class:"footer-social"), "https://www.facebook.com/TruthCustomDrums" %>

    <div class="footer-links">
      <%= link_to "contact", contacts_path %><span class="space"></span><%= link_to "terms & conditions", terms_path %><span class="space"></span><%= link_to "support", support_path %><span class="space"></span><%= link_to "admin", admin_path %>
    </div>

    <div class="footer-copy">&copy; 2016 Truth Custom Drums</div>

  </div>
</div>

app/views/layouts/_header.html.erb
<!-- DESKTOP HEADER -->
<div class="jumbotron-header" style="background: linear-gradient(rgba(50, 47, 51, 0.90), rgba(50, 47, 51, 0.90)), url('<%= @site_content %>'); background-position: center; background-size: cover; background-repeat: no-repeat;">
  <%= render 'layouts/header_nav' %>
  <div class="jumbo-head">
    <%= @title || "truth drums" %>
  </div>
</div>

app/views/layouts/_header_nav.html.erb
<div class="container-fluid">
	<div class="row">
		<div class="text-center">
				<%=link_to image_tag('sm-logo.png', class:"brand"), root_path %>
		</div>

		<div class="m_basement">
			<a href="#" onclick="toggle_visibility('nav-toggle');">&#9776;</a>
		</div>

		<div class="text-center">
			<ul class="truth-nav">
				<li><%= link_to "Drums", root_path %></li>
				<li><%= link_to "Shop", "http://truthdrums.storenvy.com/" %></li>
				<li><%= link_to "Artists", artists_path %></li>
				<li><%= link_to "Company", company_path %></li>
				<li><%= link_to "Contact", contacts_path %></li>
			</ul>

		</div>
</div>
</div>

app/views/layouts/_m_header.html.erb
<div class="mobile-truth-nav" id="nav-toggle">
	<div class="container">
		<div class="row">

			<div class="text-center">
					<%=link_to image_tag('m_logo.png', class:"m_brand"), root_path %>
			</div>

			<div class="m_close">
				<a href="#" onclick="toggle_visibility('nav-toggle');">&times;</a>
			</div>

			<div class="text-center">
				<ul class="m_truth-nav">
					<li><%= link_to "Drums", root_path %></li>
					<li><%= link_to "Shop", "http://truthdrums.storenvy.com/" %></li>
					<li><%= link_to "Artists", artists_path %></li>
					<li><%= link_to "Company", company_path %></li>
					<li><%= link_to "Contact", contacts_path %></li>
				</ul>
			</div>

		</div>
	</div>
</div>

app/views/layouts/_show_header.html.erb
<div class="container-fluid basic-header">
  <div class="row">
    <div class="text-center">
        <%=link_to image_tag('m_logo.png', class:"basic-brand"), root_path %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Truth Custom Drums</title>
  <%= stylesheet_link_tag    'application', 'https://fonts.googleapis.com/css?family=Montserrat', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent" />
	<link rel="apple-touch-icon" href="apple-touch-icon.png">
</head>
<body>

  <!-- MOBILE HEADER -->
  <%= render 'layouts/m_header' %>

  <% if @is_admin %>
  <%= render 'layouts/admin_header' %>
  <% elsif controller.controller_name == "artists" && controller.action_name == "show" %>
  <%= render 'layouts/artist_header' %>
  <% elsif controller.controller_name == "drums" && controller.action_name == "show" %>
  <%= render 'layouts/show_header' %>
  <% else %>
  <%= render 'layouts/header' %>
  <% end %>

  <%= yield %>

  <!-- FOOTER -->
  <% if !@is_admin %>
  <%= render 'layouts/footer' %>
  <% end %>

<script type="text/javascript">
<!--
    function toggle_visibility(id) {
       var e = document.getElementById(id);
       if(e.style.display == 'block')
          e.style.display = 'none';
       else
          e.style.display = 'block';
    }
//-->
</script>

</body>
</html>